/* Generated by Vercel build. Public key only; never place service_role/secret here. */
window.SMART_QC_CONFIG = {
  "supabase": {
    "url": "https://pjvqaylokypsujoovvco.supabase.co",
    "key": "sb_publishable_WrP_LOhJFMuIP6rjhMtVbg_Y-drtV2X",
    "workspace": "smartqc-qyh-shared"
  }
};
